---
networkRows: 4
networkCols: 3

foxNetworkStages: 3

foxNodeFifos:
  peToNetwork: 8
  networkToPe: 1024

resultNodeCoord:
  x: 0
  y: 0

resultNodeFifos:
  peToNetwork: 8
  networkToPe: 1024

resultUartFifoDepth: 32678

romNodeCoord:
  x: 0
  y: 3

packetFormat:
  multicastGroupBits: 1
  multicastCoordBits: 3
  doneFlagBits: 1
  resultFlagBits: 1
  matrixTypeBits: 1
  matrixCoordBits: 8
  matrixElementBits: 32

useMatrixInitFile: True

multicastAvailable: True
useMulticast: True
multicastConfig:
  multicastGroupNodes: 3
  multicastNetworkRows: 3
  multicastNetworkCols: 1
  multicastFifoDepth: 3
