---
networkRows: 2
networkCols: 2

foxNetworkStages: 2

resultNodeCoord:
  x: 0
  y: 0

romNodeCoord:
  x: 0
  y: 2

packetFormat:
  multicastGroupBits: 1
  multicastCoordBits: 2
  doneFlagBits: 1
  resultFlagBits: 1
  matrixTypeBits: 1
  matrixCoordBits: 8
  matrixElementBits: 32

useMatrixInitFile: True

useMulticast: True
multicastConfig:
  multicastGroupNodes: 2
  multicastNetworkRows: 2
  multicastNetworkCols: 1
