---
charIo:
  - name: char
    direction: output
    width: 8
  - name: char_output_ready
    direction: input
    width: 8

peToNetworkIo:

networkToPeIo:

nodeIo:
  - name: matrix_init_from_file
    direction: input
    width: 8

matrixIo:
  - name: matrix
    direction: output
    width: 32
  - name: matrix_end_row
    direction: output
    width: 8
  - name: matrix_end
    direction: output
    width: 8
  - name: matrix_init_type
    direction: input
    width: 8
  - name: matrix_init_x_coord
    direction: input
    width: 8
  - name: matrix_init_y_coord
    direction: input
    width: 8
  - name: matrix_init_element
    direction: input
    width: 32
  - name: matrix_init_read
    direction: output
    width: 8
  - name: matrix_multiply_done
    direction: output
    width: 8

networkIo:
